### ISSUE TITLE
Translate #[deprecated] on Rust functions to deprecated attribute 

### ISSUE THREAD

**Issue by MarkMcCaskey** [mozilla/cbindgen#408]
Hello!  Thanks for making and maintaining `cbindgen`, it's very useful!

We have a C API and would like to mark some of our older functions as deprecated, in Rust this can be done with the [deprecated](https://doc.rust-lang.org/edition-guide/rust-2018/the-compiler/an-attribute-for-deprecation.html) attribute.  There is also a [deprecated](https://gcc.gnu.org/onlinedocs/gcc-4.7.0/gcc/Function-Attributes.html) [attribute](https://clang.llvm.org/docs/LanguageExtensions.html#messages-on-deprecated-and-unavailable-attributes) [in](https://docs.microsoft.com/en-us/cpp/preprocessor/deprecated-c-cpp?view=vs-2019) C.  Unfortunately it's not standardized and it appears that some compilers don't support it.

It seems like for this to be more portable, we'd have to generate some preprocessor logic.

Another nice to have feature would be to be able to put all the deprecated functions in a separate header file so that the user has to opt-in to use them, too.  The progression for us would then be, mark them as deprecated, move them to a separate `deprecated.h`, and then remove them.

What are your thoughts on deprecation with cbindgen?  Maybe there's a better solution!

**Comment by emilio** [comment]
So I think this should mostly work if you annotate your functions with `cbindgen:prefix` / `cbindgen:suffix`, so like:

```rust
/// cbindgen:prefix=DEPRECATED
#[no_mangle]
pub extern "C" fn func() {}
```

will generate:

```c
DEPRECATED void func();
```

And `DEPRECATED` can be a macro your project defines as suited.

We could automate this even more, similar to the `must_use` code that exists in the repo already.

`#[deprecated]` is a bit harder because it has a message argument, so we'd need to define how to distinguish `#[deprecated]` from `#[deprecated = "use something else"]` from `#[deprecated(since = "foo", note = "bar")]`...

**Comment by emilio** [comment]
Another thing to note is that in rust, `#[deprecated]` applies to basically anything (fields, structs, enums, etc). It's not clear to me whether we need different annotations for each of them in C, like we have for `must_use`, or not.

**Comment by Hywan** [comment]
I've quickly written a new crate named `cbindgen-deprecated-attribute` which provides the procedural macro `#[cbindgen-deprecated(since = "…", note = "…")]`, https://github.com/Hywan/wasmer/compare/feat-runtime-c-api-deprecated...Hywan:feat-cbindgen-deprecated-attribute?expand=1. This `#[cbindgen-deprecated]` proc macro automatically generates the

```rust
/// cbindgen:prefix=CBINDGEN_DEPRECATED(#note) 
```

doc comment, in addition to the Rust

```rust
#[deprecated(since = #since, note = #note)]
```

attribute. On the C/C++ side, cross-compilers definitions for the `CBINDGEN_DEPRECATED` macro are provided.

It works with `cargo expand` but not with `cbindgen` because the code isn't expanded by `cbindgen` before generating the C/C++ headers. Any idea how to solve this problem @emilio? Thanks for the excellent project!

**Comment by emilio** [comment]
I think the best way to deal with this is just like we deal with `#[must_use]` and co. Dealing with functions only for now as your crate does is fine.

But basically you'd expand `AnnotationSet` to handle `deprecated` the same way as `must_use`, and add config items to get the macro name (so `config.function.deprecated`, for consistency, probably).

Then you just emit it like this pseudo-code:

```
if func.annotations.deprecated {
    let message = func.annotations.deprecation_message.as_ref().unwrap_or("");
    if let Some(ref macro) = config.functions.deprecated {
        write!(out, " {}({})", macro, message);
    }
}
```

Or such.

**Comment by Hywan** [comment]
\o/
