### ISSUE TITLE
cbindgen 0.25.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [mozilla/cbindgen#869]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
$ RUST_BACKTRACE=1 /opt/homebrew/Cellar/cbindgen/0.25.0/bin/cbindgen extern.rs
thread 'main' panicked at 'Mismatch between definition and access of `INPUT`. Could not downcast to TypeId { t: 7771347022962880447 }, need to downcast to TypeId { t: 867696335071021513 }
', /Users/rui/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.4/src/parser/error.rs:32:9
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: cbindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5976963453/job/16216109639?pr=140466
relates to Homebrew/homebrew-core#140466

**Comment by jschwe** [comment]
Could you check again? The upgrade to clap 4 was reverted and tag v0.25.0 was updated, so probably this issue is solved by now.

**Comment by chenrui333** [comment]
doing it now.

**Comment by chenrui333** [comment]
@jschwe also 0.25.0 did not get marked as `latest release`, can you help with that as well? Thanks!

**Comment by chenrui333** [comment]
@jschwe build works for me now.

**Comment by chenrui333** [comment]
once you have done with the release, we can close this ticket. :)

**Comment by jschwe** [comment]
> also 0.25.0 did not get marked as latest release,

Just to clarify, are you referring to Github Releases? There was no Github Release created for v0.25.0 (and I don't have permissions to do so). v0.25.0 is however already [released to crates.io](https://crates.io/crates/cbindgen/), so maybe that is already enough for you? Otherwise you would need to ping emilio and ask for a GitHub release.

**Comment by chenrui333** [comment]
yeah, I was referring to the github releases, unfortunately, the crates.io is not good enough for releasing on the homebrew-core side these day.

cc @emilio 🙏

**Comment by emilio** [comment]
@chenrui333 the git tag should be fixed (it was wrong for a minimal amount of time).

https://github.com/mozilla/cbindgen/releases/tag/v0.25.0 points to dd9a550152cd162a3aa01757a55dd22fc56d0d8a which contains 0529d215e7a1b2ad94ca166c1b26ad96f10e4a1c.

**Comment by jschwe** [comment]
@emilio From my understanding @chenrui333 was requesting to create a release on [this page](https://github.com/mozilla/cbindgen/releases). The CI job to create the (draft) release failed, so it would need to be created manually for this release. For further releases (once #871 is merged) it should work semi-automatically again, since CI will create a draft-release and the maintainer just needs to double-check and confirm the release description.

**Comment by chenrui333** [comment]
> @emilio From my understanding @chenrui333 was requesting to create a release on [this page](https://github.com/mozilla/cbindgen/releases).

yeah, exactly, it would be good to have the release shown in the github side. thanks! 🙏

**Comment by chenrui333** [comment]
Any appetite for a github release? Thanks!

**Comment by emilio** [comment]
Welp, thanks for the ping, was traveling so I forgot about this. https://github.com/mozilla/cbindgen/releases/tag/v0.25.0

**Comment by chenrui333** [comment]
Thanks @emilio!
