### ISSUE TITLE
How can i offline install 

### ISSUE THREAD

**Issue by frkn4129** [mozilla/cbindgen#918]
How can I install cbindgen on a machine without internet access?

**Comment by jschwe** [comment]
There is not really any difference to any other normal Rust project. You could use [cargo vendor](https://doc.rust-lang.org/cargo/commands/cargo-vendor.html), and copy the sources to the offline machine and compile there. Alternatively, you could also (cross-) compile cbindgen for your target machine and copy the binary. Compiling for a different machine can be difficult, since your local machine might e.g. have a newer glibc than the target machine, which could lead to issues when executing the binary on the target machine. If your target system runs Linux, then compiling for `-musl` usually avoids such problems.
